### ISSUE TITLE
Bewegung des Bohrers

### ISSUE THREAD

**Issue by PhilippFaber** [PhilippFaber/sg-drill#1]
Der Bohrer soll folgende Bewegung ausführen:

- [x] ohne Knopfdruck soll eine Drehbewegung nach links ausgeführt werden (Rotationsbewegung, der Sprite sollte gleichzeitig ebenfalls rotieren.
- [x] Bei Knopfdruck verändert sich die Bewegung nach rechts.
- [x] Der Bohrer kann nicht nach oben bohren
- [x] Der Bohrer kann den Bildschirm nicht verlassen
- [x] Die y-Variable soll als aktueller Score ausgelesen werden, um die zurückgelegte Distanz darzustellen.
- [x] An einem gewissen Punkt soll das Spiel automatisch enden (Erdkern erreicht)

**Comment by IIITyforIII** [comment]
Die Bewegung des Bohrers ist grundsätzlich fertig (movementSpeed ist testweise sehr niedrig)

**Comment by PhilippFaber** [comment]
Erledigt mit #17
